%%%% This code generates a Customized G-code for Uniform Hexagonal and Diamond frame structures %%%%
%%%% Customized tool-path is generated by defining a continuous nodal path with uniform flow rate %%
%%%% Written By Dhanashri Desai (3rd year,MTech(R),ME,IISc) during 1 Aug'22 to 10 Oct'22 for the fulfillment of MTech(R) Thesis %%%%
%%%% Modified by Jaydeep Pawar (2nd year,MTech,CSA,IISc) for generalization w.r.t. no of cells %%%%

%%% This function contains the parametric data for unit cell %%%
% which are passed as argumemnts to user-defined functions 
% to generate eventually the G-code file %%%

clear; clc; close all; % Housekeeping commands
t=3; theta=60; rho_rel=0.15; % parameters of unit cell
nH=5; nV=4; % no of cells in horizontal and vertical direction 
CellType='BendingDominatedHexagon'; %      StretchDominatedDiamond
E0=5.87; dLdE=60; % uniform rate at which motor feed increases
nL=1; % no. of layers to be printed

% generate grid of nodes and elements
[l,lh,lv,ne,nn,nodeID,nx,ny,Nr,Nc,lhD,lvD] = ...
Generate2DGrid(CellType,nH,nV,t,rho_rel,theta);

% generate continuous nodal path
[NodalPath] = GenerateNodalPath(CellType,nn,nH,nV);

% generate uniform flow rate data according to nodal path
[E,nExtr] = GenerateFeedRate(CellType,E0,ne,dLdE,l,lv, ...
    lhD,lvD,nH,nV,Nr,nL);

% generate G-code file
WriteToFile(CellType,NodalPath,nx,ny,E,nH,nV,nExtr,nL);